# fly.toml
app = "ChatBot_LLM"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000

[build]
  builder = "heroku/buildpacks:18"

[[build.env]]
  name = "FLY_REDIS_URL"
  value = "your-redis-url"

[[build.env]]
  name = "FLY_PG_URL"
  value = "your-postgres-url"
